[header]
path = "licenserc.header.txt"

[files]
includes = [
  "crates/**/*.rs",
  "ppvm-python/src/**/*.py",
]

excludes = [
  "**/target/**",
  "**/node_modules/**",
  "**/.venv/**",
  "**/generated/**",
  "**/*.lock",
  "docs/**",
  "examples/**",
  "julia-benchmarks/**",
]

[props]
inceptionYear = 2026
copyrightOwner = "The PPVM Authors"
