headerPath = "licenserc.header.txt"

includes = [
  "crates/**/*.rs",
  "ppvm-python/src/**/*.py",
]

excludes = [
  "**/target/**",
  "**/node_modules/**",
  "**/.venv/**",
  "**/generated/**",
  "**/*.lock",
  "docs/**",
  "examples/**",
  "julia-benchmarks/**",
]

useDefaultMapping = true

[properties]
inceptionYear = 2026
copyrightOwner = "The PPVM Authors"
