site_name: ppvm
# repo_url: https://github.com/QuEraComputing/ppvm
site_description: >-
  ppvm — a fast Heisenberg-picture Pauli propagation simulator

docs_dir: docs

nav:
  - Home: index.md
  - Installation: install.md
  - Pauli Propagation:
    - pauli_sum/index.md
    - Loss channel details: pauli_sum/loss.md
  - Generalized Tableau: generalized_tableau.md
  - Examples:
    - examples/index.md
    - Trotter simulation: examples/trotter.py
    - Magic State Distillation: examples/msd.py
  - API Reference:
    - api/index.md
    - api/ppvm/paulisum.md
    - api/ppvm/generalized_tableau.md

theme:
  name: material
  font:
    text: Lato
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.follow

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: false
            separate_signature: true
            merge_init_into_class: true
            extensions:
              - griffe_inherited_docstrings
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_options:
              ignore_init_summary: true
  - search:
      separator: '[\s\-,:!=\[\:)"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
      ignore: ['scripts/*']

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
