from collections.abc import Sequence

class _PauliSumBase:
    def __init__(
        self,
        n_qubits: int,
        min_abs_coeff: float = 1e-10,
        max_pauli_weight: int = ...,
        max_loss_weight: int = ...,
        terms: list[str] = ...,
        coefficients: list[float] = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> _PauliSumBase: ...
    def __deepcopy__(self, memo: object) -> _PauliSumBase: ...
    def __len__(self) -> int: ...
    def trace(self, pattern: str) -> float: ...
    def overlap_with_zero(self) -> float: ...
    def overlap(self, other: _PauliSumBase) -> float: ...
    def truncate(self) -> None: ...
    # Every PauliSum gate/channel exposes a `truncate: bool = True` kwarg: when
    # true (the default) the active truncation strategy fires immediately after
    # the op. See `ppvm.mixins` and `crates/ppvm-python-native/src/interface.rs`.
    def x(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def y(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def z(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def h(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def s(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def cnot(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def cx(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def zcx(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def cz(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def zcz(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def cy(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def zcy(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def s_dag(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def sqrt_x(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def sqrt_y(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def sqrt_x_dag(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def sqrt_y_dag(self, targets: Sequence[int], truncate: bool = True) -> None: ...
    def rx(self, targets: Sequence[int], theta: float, truncate: bool = True) -> None: ...
    def ry(self, targets: Sequence[int], theta: float, truncate: bool = True) -> None: ...
    def rz(self, targets: Sequence[int], theta: float, truncate: bool = True) -> None: ...
    def rxx(self, targets: Sequence[int], theta: float, truncate: bool = True) -> None: ...
    def ryy(self, targets: Sequence[int], theta: float, truncate: bool = True) -> None: ...
    def rzz(self, targets: Sequence[int], theta: float, truncate: bool = True) -> None: ...
    def x_error(self, targets: Sequence[int], p: float, truncate: bool = True) -> None: ...
    def y_error(self, targets: Sequence[int], p: float, truncate: bool = True) -> None: ...
    def z_error(self, targets: Sequence[int], p: float, truncate: bool = True) -> None: ...
    def pauli_error(
        self, targets: Sequence[int], p: Sequence[float], truncate: bool = True
    ) -> None: ...
    def two_qubit_pauli_error(
        self, targets: Sequence[int], p: Sequence[float], truncate: bool = True
    ) -> None: ...
    def depolarize1(self, targets: Sequence[int], p: float, truncate: bool = True) -> None: ...
    def depolarize2(self, targets: Sequence[int], p: float, truncate: bool = True) -> None: ...
    def amplitude_damping(self, addr0: int, gamma: float, truncate: bool = True) -> None: ...
    def terms(self) -> list[tuple[str, float]]: ...
    def weights(self) -> list[tuple[str, int]]: ...
    def current_max_weight(self) -> int: ...

class _PauliSumLossBase(_PauliSumBase):
    def loss_channel(self, addr0: int, p: float, truncate: bool = True) -> None: ...
    def correlated_loss_channel(
        self, addr0: int, addr1: int, p: Sequence[float], truncate: bool = True
    ) -> None: ...
    def reset_loss_channel(self, addr0: int, truncate: bool = True) -> None: ...

class PauliSumIndexMapFxHash0(_PauliSumBase): ...
class PauliSumIndexMapFxHash1(_PauliSumBase): ...
class PauliSumIndexMapFxHash2(_PauliSumBase): ...
class PauliSumIndexMapFxHash3(_PauliSumBase): ...
class PauliSumIndexMapFxHash4(_PauliSumBase): ...
class PauliSumIndexMapFxHash5(_PauliSumBase): ...
class PauliSumIndexMapFxHash6(_PauliSumBase): ...
class PauliSumIndexMapFxHash7(_PauliSumBase): ...
class PauliSumIndexMapFxHash8(_PauliSumBase): ...
class PauliSumIndexMapFxHash9(_PauliSumBase): ...
class PauliSumIndexMapFxHash10(_PauliSumBase): ...
class PauliSumIndexMapFxHash11(_PauliSumBase): ...
class PauliSumIndexMapFxHash12(_PauliSumBase): ...
class PauliSumIndexMapFxHash13(_PauliSumBase): ...
class PauliSumIndexMapFxHash14(_PauliSumBase): ...
class PauliSumIndexMapFxHash15(_PauliSumBase): ...
class PauliSumLossIndexMapFxHash0(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash1(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash2(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash3(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash4(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash5(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash6(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash7(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash8(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash9(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash10(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash11(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash12(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash13(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash14(_PauliSumLossBase): ...
class PauliSumLossIndexMapFxHash15(_PauliSumLossBase): ...

class _GeneralizedTableauBase:
    def __init__(
        self,
        n_qubits: int,
        min_abs_coeff: float = 1e-10,
        seed: int | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> _GeneralizedTableauBase: ...
    def __deepcopy__(self, memo: object) -> _GeneralizedTableauBase: ...
    def measure(self, addr0: int) -> int: ...
    def measure_many(self, targets: Sequence[int]) -> list[int]: ...
    def current_measurement_record(self) -> list[int]: ...
    def x(self, targets: Sequence[int]) -> None: ...
    def y(self, targets: Sequence[int]) -> None: ...
    def z(self, targets: Sequence[int]) -> None: ...
    def h(self, targets: Sequence[int]) -> None: ...
    def s(self, targets: Sequence[int]) -> None: ...
    def s_dag(self, targets: Sequence[int]) -> None: ...
    def sqrt_x(self, targets: Sequence[int]) -> None: ...
    def sqrt_x_dag(self, targets: Sequence[int]) -> None: ...
    def sqrt_y(self, targets: Sequence[int]) -> None: ...
    def sqrt_y_dag(self, targets: Sequence[int]) -> None: ...
    def t(self, targets: Sequence[int]) -> None: ...
    def t_dag(self, targets: Sequence[int]) -> None: ...
    def cnot(self, targets: Sequence[int]) -> None: ...
    def cx(self, targets: Sequence[int]) -> None: ...
    def zcx(self, targets: Sequence[int]) -> None: ...
    def cy(self, targets: Sequence[int]) -> None: ...
    def zcy(self, targets: Sequence[int]) -> None: ...
    def cz(self, targets: Sequence[int]) -> None: ...
    def zcz(self, targets: Sequence[int]) -> None: ...
    def rx(self, targets: Sequence[int], theta: float) -> None: ...
    def ry(self, targets: Sequence[int], theta: float) -> None: ...
    def rz(self, targets: Sequence[int], theta: float) -> None: ...
    def u3(self, addr0: int, theta: float, phi: float, lam: float) -> None: ...
    def rxx(self, targets: Sequence[int], theta: float) -> None: ...
    def ryy(self, targets: Sequence[int], theta: float) -> None: ...
    def rzz(self, targets: Sequence[int], theta: float) -> None: ...
    def x_error(self, targets: Sequence[int], p: float) -> None: ...
    def y_error(self, targets: Sequence[int], p: float) -> None: ...
    def z_error(self, targets: Sequence[int], p: float) -> None: ...
    def pauli_error(self, targets: Sequence[int], p: Sequence[float]) -> None: ...
    def depolarize1(self, targets: Sequence[int], p: float) -> None: ...
    def depolarize2(self, targets: Sequence[int], p: float) -> None: ...
    def two_qubit_pauli_error(self, targets: Sequence[int], p: Sequence[float]) -> None: ...
    def loss_channel(self, addr0: int, p: float) -> None: ...
    def correlated_loss_channel(self, addr0: int, addr1: int, p: Sequence[float]) -> None: ...
    def reset_loss_channel(self, addr0: int) -> None: ...
    def reset(self, targets: Sequence[int]) -> None: ...
    def reset_x(self, targets: Sequence[int]) -> None: ...
    def reset_y(self, targets: Sequence[int]) -> None: ...
    def reset_z(self, targets: Sequence[int]) -> None: ...
    def is_lost(self, addr0: int) -> bool: ...
    def loss_values(self) -> list[bool]: ...
    def run(self, prog: StimProgram) -> list[int]: ...
    @staticmethod
    def sample(
        prog: StimProgram,
        n_qubits: int,
        min_abs_coeff: float = 1e-10,
        num_shots: int = 1,
        seed: int | None = None,
    ) -> list[list[int]]: ...
    def fork(self, seed: int | None = None) -> _GeneralizedTableauBase: ...

class StimProgram:
    @staticmethod
    def parse(src: str) -> StimProgram: ...
    @staticmethod
    def from_file(path: str) -> StimProgram: ...
    def __repr__(self) -> str: ...

class GeneralizedTableau1(_GeneralizedTableauBase): ...
class GeneralizedTableau2(_GeneralizedTableauBase): ...
class GeneralizedTableau3(_GeneralizedTableauBase): ...
class GeneralizedTableau4(_GeneralizedTableauBase): ...
class GeneralizedTableau5(_GeneralizedTableauBase): ...
class GeneralizedTableau6(_GeneralizedTableauBase): ...
class GeneralizedTableau7(_GeneralizedTableauBase): ...
class GeneralizedTableau8(_GeneralizedTableauBase): ...
class GeneralizedTableau9(_GeneralizedTableauBase): ...
class GeneralizedTableau10(_GeneralizedTableauBase): ...
class GeneralizedTableau11(_GeneralizedTableauBase): ...
class GeneralizedTableau12(_GeneralizedTableauBase): ...
class GeneralizedTableau13(_GeneralizedTableauBase): ...
class GeneralizedTableau14(_GeneralizedTableauBase): ...
class GeneralizedTableau15(_GeneralizedTableauBase): ...
class GeneralizedTableau16(_GeneralizedTableauBase): ...
class GeneralizedTableau17(_GeneralizedTableauBase): ...
class GeneralizedTableau18(_GeneralizedTableauBase): ...
class GeneralizedTableau19(_GeneralizedTableauBase): ...
class GeneralizedTableau20(_GeneralizedTableauBase): ...
class GeneralizedTableau21(_GeneralizedTableauBase): ...
class GeneralizedTableau22(_GeneralizedTableauBase): ...
class GeneralizedTableau23(_GeneralizedTableauBase): ...
class GeneralizedTableau24(_GeneralizedTableauBase): ...
class GeneralizedTableau25(_GeneralizedTableauBase): ...
class GeneralizedTableau26(_GeneralizedTableauBase): ...
class GeneralizedTableau27(_GeneralizedTableauBase): ...
class GeneralizedTableau28(_GeneralizedTableauBase): ...
class GeneralizedTableau29(_GeneralizedTableauBase): ...
class GeneralizedTableau30(_GeneralizedTableauBase): ...
class GeneralizedTableau31(_GeneralizedTableauBase): ...
class GeneralizedTableau32(_GeneralizedTableauBase): ...

class _TableauSumSamplerBase:
    def __copy__(self) -> _TableauSumSamplerBase: ...
    def __deepcopy__(self, memo: object) -> _TableauSumSamplerBase: ...
    def sample(self) -> list[int]: ...
    def sample_shots(self, num_shots: int) -> list[list[int]]: ...

class _GeneralizedTableauSumBase:
    def __init__(
        self,
        n_qubits: int,
        min_abs_coeff: float = 1e-10,
        sum_cutoff: float = 1e-8,
        seed: int | None = None,
    ) -> None: ...
    def __copy__(self) -> _GeneralizedTableauSumBase: ...
    def __deepcopy__(self, memo: object) -> _GeneralizedTableauSumBase: ...
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def measure(self, addr0: int) -> tuple[float, float, float]: ...
    def x(self, targets: Sequence[int]) -> None: ...
    def y(self, targets: Sequence[int]) -> None: ...
    def z(self, targets: Sequence[int]) -> None: ...
    def h(self, targets: Sequence[int]) -> None: ...
    def s(self, targets: Sequence[int]) -> None: ...
    def s_dag(self, targets: Sequence[int]) -> None: ...
    def sqrt_x(self, targets: Sequence[int]) -> None: ...
    def sqrt_x_dag(self, targets: Sequence[int]) -> None: ...
    def sqrt_y(self, targets: Sequence[int]) -> None: ...
    def sqrt_y_dag(self, targets: Sequence[int]) -> None: ...
    def cnot(self, targets: Sequence[int]) -> None: ...
    def cx(self, targets: Sequence[int]) -> None: ...
    def zcx(self, targets: Sequence[int]) -> None: ...
    def cy(self, targets: Sequence[int]) -> None: ...
    def zcy(self, targets: Sequence[int]) -> None: ...
    def cz(self, targets: Sequence[int]) -> None: ...
    def zcz(self, targets: Sequence[int]) -> None: ...
    def t(self, targets: Sequence[int]) -> None: ...
    def t_dag(self, targets: Sequence[int]) -> None: ...
    def rx(self, targets: Sequence[int], theta: float) -> None: ...
    def ry(self, targets: Sequence[int], theta: float) -> None: ...
    def rz(self, targets: Sequence[int], theta: float) -> None: ...
    def u3(self, addr0: int, theta: float, phi: float, lam: float) -> None: ...
    def rxx(self, targets: Sequence[int], theta: float) -> None: ...
    def ryy(self, targets: Sequence[int], theta: float) -> None: ...
    def rzz(self, targets: Sequence[int], theta: float) -> None: ...
    def x_error(self, targets: Sequence[int], p: float) -> None: ...
    def y_error(self, targets: Sequence[int], p: float) -> None: ...
    def z_error(self, targets: Sequence[int], p: float) -> None: ...
    def pauli_error(self, targets: Sequence[int], p: Sequence[float]) -> None: ...
    def depolarize1(self, targets: Sequence[int], p: float) -> None: ...
    def depolarize2(self, targets: Sequence[int], p: float) -> None: ...
    def two_qubit_pauli_error(self, targets: Sequence[int], p: Sequence[float]) -> None: ...
    def loss_channel(self, addr0: int, p: float) -> None: ...
    def correlated_loss_channel(self, addr0: int, addr1: int, p: Sequence[float]) -> None: ...
    def reset_loss_channel(self, addr0: int) -> None: ...
    def reset(self, targets: Sequence[int]) -> None: ...
    def truncate(self) -> None: ...
    def sampler(self) -> _TableauSumSamplerBase: ...

class GeneralizedTableauSum1(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum2(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum3(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum4(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum5(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum6(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum7(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum8(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum9(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum10(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum11(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum12(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum13(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum14(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum15(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum16(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum17(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum18(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum19(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum20(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum21(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum22(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum23(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum24(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum25(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum26(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum27(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum28(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum29(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum30(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum31(_GeneralizedTableauSumBase): ...
class GeneralizedTableauSum32(_GeneralizedTableauSumBase): ...
class TableauSumSampler1(_TableauSumSamplerBase): ...
class TableauSumSampler2(_TableauSumSamplerBase): ...
class TableauSumSampler3(_TableauSumSamplerBase): ...
class TableauSumSampler4(_TableauSumSamplerBase): ...
class TableauSumSampler5(_TableauSumSamplerBase): ...
class TableauSumSampler6(_TableauSumSamplerBase): ...
class TableauSumSampler7(_TableauSumSamplerBase): ...
class TableauSumSampler8(_TableauSumSamplerBase): ...
class TableauSumSampler9(_TableauSumSamplerBase): ...
class TableauSumSampler10(_TableauSumSamplerBase): ...
class TableauSumSampler11(_TableauSumSamplerBase): ...
class TableauSumSampler12(_TableauSumSamplerBase): ...
class TableauSumSampler13(_TableauSumSamplerBase): ...
class TableauSumSampler14(_TableauSumSamplerBase): ...
class TableauSumSampler15(_TableauSumSamplerBase): ...
class TableauSumSampler16(_TableauSumSamplerBase): ...
class TableauSumSampler17(_TableauSumSamplerBase): ...
class TableauSumSampler18(_TableauSumSamplerBase): ...
class TableauSumSampler19(_TableauSumSamplerBase): ...
class TableauSumSampler20(_TableauSumSamplerBase): ...
class TableauSumSampler21(_TableauSumSamplerBase): ...
class TableauSumSampler22(_TableauSumSamplerBase): ...
class TableauSumSampler23(_TableauSumSamplerBase): ...
class TableauSumSampler24(_TableauSumSamplerBase): ...
class TableauSumSampler25(_TableauSumSamplerBase): ...
class TableauSumSampler26(_TableauSumSamplerBase): ...
class TableauSumSampler27(_TableauSumSamplerBase): ...
class TableauSumSampler28(_TableauSumSamplerBase): ...
class TableauSumSampler29(_TableauSumSamplerBase): ...
class TableauSumSampler30(_TableauSumSamplerBase): ...
class TableauSumSampler31(_TableauSumSamplerBase): ...
class TableauSumSampler32(_TableauSumSamplerBase): ...
