# SPDX-FileCopyrightText: 2026 The PPVM Authors
# SPDX-License-Identifier: Apache-2.0

from typing import Union

from . import _core

GeneralizedTableauInterface = Union[
    _core.GeneralizedTableau1,
    _core.GeneralizedTableau2,
    _core.GeneralizedTableau3,
    _core.GeneralizedTableau4,
    _core.GeneralizedTableau5,
    _core.GeneralizedTableau6,
    _core.GeneralizedTableau7,
    _core.GeneralizedTableau8,
    _core.GeneralizedTableau9,
    _core.GeneralizedTableau10,
    _core.GeneralizedTableau11,
    _core.GeneralizedTableau12,
    _core.GeneralizedTableau13,
    _core.GeneralizedTableau14,
    _core.GeneralizedTableau15,
    _core.GeneralizedTableau16,
    _core.GeneralizedTableau17,
    _core.GeneralizedTableau18,
    _core.GeneralizedTableau19,
    _core.GeneralizedTableau20,
    _core.GeneralizedTableau21,
    _core.GeneralizedTableau22,
    _core.GeneralizedTableau23,
    _core.GeneralizedTableau24,
    _core.GeneralizedTableau25,
    _core.GeneralizedTableau26,
    _core.GeneralizedTableau27,
    _core.GeneralizedTableau28,
    _core.GeneralizedTableau29,
    _core.GeneralizedTableau30,
    _core.GeneralizedTableau31,
    _core.GeneralizedTableau32,
]


GeneralizedTableauSumInterface = Union[
    _core.GeneralizedTableauSum1,
    _core.GeneralizedTableauSum2,
    _core.GeneralizedTableauSum3,
    _core.GeneralizedTableauSum4,
    _core.GeneralizedTableauSum5,
    _core.GeneralizedTableauSum6,
    _core.GeneralizedTableauSum7,
    _core.GeneralizedTableauSum8,
    _core.GeneralizedTableauSum9,
    _core.GeneralizedTableauSum10,
    _core.GeneralizedTableauSum11,
    _core.GeneralizedTableauSum12,
    _core.GeneralizedTableauSum13,
    _core.GeneralizedTableauSum14,
    _core.GeneralizedTableauSum15,
    _core.GeneralizedTableauSum16,
    _core.GeneralizedTableauSum17,
    _core.GeneralizedTableauSum18,
    _core.GeneralizedTableauSum19,
    _core.GeneralizedTableauSum20,
    _core.GeneralizedTableauSum21,
    _core.GeneralizedTableauSum22,
    _core.GeneralizedTableauSum23,
    _core.GeneralizedTableauSum24,
    _core.GeneralizedTableauSum25,
    _core.GeneralizedTableauSum26,
    _core.GeneralizedTableauSum27,
    _core.GeneralizedTableauSum28,
    _core.GeneralizedTableauSum29,
    _core.GeneralizedTableauSum30,
    _core.GeneralizedTableauSum31,
    _core.GeneralizedTableauSum32,
]

TableauSumSamplerInterface = Union[
    _core.TableauSumSampler1,
    _core.TableauSumSampler2,
    _core.TableauSumSampler3,
    _core.TableauSumSampler4,
    _core.TableauSumSampler5,
    _core.TableauSumSampler6,
    _core.TableauSumSampler7,
    _core.TableauSumSampler8,
    _core.TableauSumSampler9,
    _core.TableauSumSampler10,
    _core.TableauSumSampler11,
    _core.TableauSumSampler12,
    _core.TableauSumSampler13,
    _core.TableauSumSampler14,
    _core.TableauSumSampler15,
    _core.TableauSumSampler16,
    _core.TableauSumSampler17,
    _core.TableauSumSampler18,
    _core.TableauSumSampler19,
    _core.TableauSumSampler20,
    _core.TableauSumSampler21,
    _core.TableauSumSampler22,
    _core.TableauSumSampler23,
    _core.TableauSumSampler24,
    _core.TableauSumSampler25,
    _core.TableauSumSampler26,
    _core.TableauSumSampler27,
    _core.TableauSumSampler28,
    _core.TableauSumSampler29,
    _core.TableauSumSampler30,
    _core.TableauSumSampler31,
    _core.TableauSumSampler32,
]
